In [1]:
import sys
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
sys.path.append(os.path.abspath(os.path.join('..')))

from src import calculate_nss, vasicek_zcb, vasicek_coupon_bond, vasicek_zcb_option, vasicek_coupon_bond_option
from src import cir_zcb, cir_coupon_bond, cir_zcb_option, cir_coupon_bond_option

# Nelson-Siegel-Svensson

In [2]:
# Example calculation of Nelson-Siegel-Svensson 
maturities = [0, 0.25, 0.5, 1, 2, 5, 10, 30]
a= 0.0354
b= 0.0135
c= 1.2280
d= -1.2229
tau= 1.0045
theta= 1.0181
results = calculate_nss(maturities, a=a, b=b, c=c, d=d, tau=tau, theta=theta)

display(results)

           zcy_NSS     f_NSS     p_NSS
maturity
0.00      0.048900  0.048900  1.000000
0.25      0.049338  0.049305  0.987741
0.50      0.048967  0.047657  0.975814
1.00      0.047018  0.042332  0.954070
2.00      0.042382  0.034230  0.918729
5.00      0.036470  0.033383  0.833311
10.00     0.035614  0.035330  0.700374
30.00     0.035468  0.035400  0.345055

# Vasicek

In [3]:
# Example calculation of Vasicek zero-coupon bond prices
maturities = np.array([0, 0.25, 0.5, 1, 2, 5, 10, 30])
rt = 0.03
kappa = 0.15
theta = 0.05
sigma = 0.01
vasicek_results = vasicek_zcb(T=maturities, rt=rt, kappa=kappa, theta=theta, sigma=sigma)
display(vasicek_results)

          zcb_price_vk    zcy_vk
maturity
0.00          1.000000  0.030000
0.25          0.992436  0.030369
0.50          0.984754  0.030728
1.00          0.969075  0.031413
2.00          0.936753  0.032668
5.00          0.836594  0.035683
10.00         0.676938  0.039017
30.00         0.266235  0.044113

In [4]:
# Example calculation of Vasicek zcoupon bond price
maturity = 3
coupon_rate = 0.06
frequency = 4
rt = 0.042
kappa = 0.15
theta = 0.04
sigma = 0.025
vasicek_coupon_bond_result = vasicek_coupon_bond(
    maturity=maturity,
    coupon_rate=coupon_rate,
    frequency=frequency,    
    rt=rt,
    kappa=kappa,
    theta=theta,
    sigma=sigma
)
display(vasicek_coupon_bond_result)

price                  1.052855
macaulay_duration      2.775190
stochastic_duration    2.249202
Name: bond_metrics, dtype: float64

In [5]:
#Example calculation of Vasicek zero-coupon bond option prices

T_call = 1.0  # Option maturity
T = 5       # Bond maturity
K = 0.8      # Strike price
option_type = 'call'  
rt = 0.04
kappa = 0.1
theta = 0.05    
sigma = 0.02

vasicek_option_price = vasicek_zcb_option(
    T_call=T_call,
    T=T,
    K=K,
    t=0.0,
    rt=rt,
    kappa=kappa,
    theta=theta,
    sigma=sigma,
    option_type=option_type
)
display(vasicek_option_price)

np.float64(0.051147973842328165)

In [6]:
# Example calculation of Vasicek coupon bond option prices
T_call = 1.0  # Option maturity
T = 5       # Bond maturity
coupon_rate = 0.06
frequency = 2
K = 0.8      # Strike price
option_type = 'call'  
rt = 0.04
kappa = 0.1
theta = 0.05    
sigma = 0.02
vasicek_coupon_bond_option_price = vasicek_coupon_bond_option(
    T=T,
    T_call=T_call,
    coupon_rate=coupon_rate,
    frequency=frequency,
    K=K,
    t=0.0,
    rt=rt,
    kappa=kappa,
    theta=theta,
    sigma=sigma,
    option_type=option_type)
display(vasicek_coupon_bond_option_price)

np.float64(0.2568453252090852)

# Cox-Ingersoll-Ross

In [7]:
#Example calculation of Cox-Ingersoll-Ross zero-coupon bond prices
maturities = np.array([0, 0.25, 0.5, 1, 2, 5, 10, 30])
rt = 0.03
kappa = 0.15
theta = 0.05
sigma = 0.01
cir_results = cir_zcb(T=maturities, rt=rt, kappa=kappa, theta=theta, sigma=sigma)
display(cir_results)

          zcb_price_cir   zcy_cir
maturity
0.00           1.000000  0.030000
0.25           0.992436  0.030370
0.50           0.984752  0.030731
1.00           0.969061  0.031427
2.00           0.936656  0.032720
5.00           0.835598  0.035922
10.00          0.672880  0.039619
30.00          0.255079  0.045539

In [8]:
# Example calculation of Cox-Ingersoll-Ross coupon bond prices
maturity = 3
coupon_rate = 0.05
frequency = 2
rt = 0.06
kappa = 0.2
theta = 0.04
sigma = 0.1
cir_coupon_bond_result = cir_coupon_bond(
    maturity=maturity,
    coupon_rate=coupon_rate,
    frequency=frequency,    
    rt=rt,
    kappa=kappa,
    theta=theta,
    sigma=sigma,
    face_value=100.0
)
display(cir_coupon_bond_result)

np.float64(98.53522610097669)

In [9]:
# Example calculation of Cox-Ingersoll-Ross zero coupon bond option prices
T_call = 1.0  # Option maturity
T = 3      # Bond maturity
K = 0.995      # Strike price
option_type = 'call'
rt = 0.06
kappa = 0.2
theta = 0.04
sigma = 0.1
cir_option_price = cir_zcb_option(
    T_call=T_call,
    T=T,
    K=K,
    t=0.0,
    rt=rt,
    kappa=kappa,
    theta=theta,
    sigma=sigma,
    option_type=option_type
)
display(cir_option_price)

np.float64(0.0)

In [10]:
# Example calculation of Cox-Ingersoll-Ross coupon bond option prices
T = 3    # Bond maturity
T_call=1.0  # Option maturity
K = 0.995      # Strike price
coupon_rate = 0.05
frequency = 2
rt = 0.06
kappa = 0.2
theta = 0.04
sigma = 0.1 
option_type='call'
cir_coupon_bond_option_price = cir_coupon_bond_option(
    T=T,
    T_call=T_call,
    coupon_rate=coupon_rate,
    frequency=frequency,
    K=K,
    rt=rt,
    kappa=kappa,
    theta=theta,
    sigma=sigma,
    option_type=option_type,
    t=0.0
)
display(cir_coupon_bond_option_price)

np.float64(0.012049824733491343)